//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtencionesEstadosLocal
    {
        public System.Guid id { get; set; }
        public Nullable<int> idSectorOrigen { get; set; }
        public Nullable<int> idSectorDestino { get; set; }
        public Nullable<int> idPuestoTrabajo { get; set; }
    
        public virtual AtencionesEstados AtencionesEstados { get; set; }
        public virtual Sectores Sectores { get; set; }
        public virtual Sectores Sectores1 { get; set; }
    }
}
