//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KlinicosEntities : DbContext
    {
        public KlinicosEntities()
            : base("name=KlinicosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atenciones> Atenciones { get; set; }
        public virtual DbSet<AtencionesEstados> AtencionesEstados { get; set; }
        public virtual DbSet<AtencionesEstadosLocal> AtencionesEstadosLocal { get; set; }
        public virtual DbSet<AtencionEstados> AtencionEstados { get; set; }
        public virtual DbSet<AtencionObrasSociales> AtencionObrasSociales { get; set; }
        public virtual DbSet<ClasificacionesRiesgo> ClasificacionesRiesgo { get; set; }
        public virtual DbSet<Evoluciones> Evoluciones { get; set; }
        public virtual DbSet<EvolucionesArchivos> EvolucionesArchivos { get; set; }
        public virtual DbSet<EvolucionesNOTA> EvolucionesNOTA { get; set; }
        public virtual DbSet<EvolucionesSM> EvolucionesSM { get; set; }
        public virtual DbSet<EvolucionesSOAP> EvolucionesSOAP { get; set; }
        public virtual DbSet<ObservacionAntropometrica> ObservacionAntropometrica { get; set; }
        public virtual DbSet<Observaciones> Observaciones { get; set; }
        public virtual DbSet<ProblemasSalud> ProblemasSalud { get; set; }
        public virtual DbSet<Especialidades> Especialidades { get; set; }
        public virtual DbSet<Establecimientos> Establecimientos { get; set; }
        public virtual DbSet<FormaIngreso> FormaIngreso { get; set; }
        public virtual DbSet<Profesionales> Profesionales { get; set; }
        public virtual DbSet<ConfiguracionAgenda> ConfiguracionAgenda { get; set; }
        public virtual DbSet<HistoriaPlanillaDiaria> HistoriaPlanillaDiaria { get; set; }
        public virtual DbSet<PlanillaDiaria> PlanillaDiaria { get; set; }
        public virtual DbSet<PlanillaDiarioEstado> PlanillaDiarioEstado { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<TurnoEstado> TurnoEstado { get; set; }
        public virtual DbSet<TurnosReserva> TurnosReserva { get; set; }
        public virtual DbSet<TurnoTurnoEstado> TurnoTurnoEstado { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<ProfesionalesEspecialidades> ProfesionalesEspecialidades { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosSectores> UsuariosSectores { get; set; }
        public virtual DbSet<Sectores> Sectores { get; set; }
    }
}
