//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atenciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atenciones()
        {
            this.AtencionesEstados = new HashSet<AtencionesEstados>();
            this.Evoluciones = new HashSet<Evoluciones>();
            this.Observaciones = new HashSet<Observaciones>();
        }
    
        public System.Guid id { get; set; }
        public string motivo { get; set; }
        public int edadAparente { get; set; }
        public string edadAparenteUnidad { get; set; }
        public bool conPrioridad { get; set; }
        public int idFormaIngreso { get; set; }
        public int idClasificacionRiesgo { get; set; }
        public System.Guid idPaciente { get; set; }
        public string responsable { get; set; }
        public int idParentescoResponsable { get; set; }
        public Nullable<int> idTurno { get; set; }
        public string usuarioCrea { get; set; }
        public System.DateTime fechaCrea { get; set; }
        public string usuarioModi { get; set; }
        public System.DateTime fechaModi { get; set; }
        public Nullable<System.Guid> idUltimoPacienteDomicilio { get; set; }
        public Nullable<System.Guid> idUltimoPacienteNivelInstruccion { get; set; }
        public Nullable<System.Guid> idUltimoPacienteSituacionLaboral { get; set; }
        public Nullable<System.Guid> idUltimoPacienteNacionalidad { get; set; }
        public Nullable<System.Guid> idUltimoPacienteEstadoCivil { get; set; }
        public Nullable<int> idEstablecimiento { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtencionesEstados> AtencionesEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evoluciones> Evoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observaciones> Observaciones { get; set; }
    }
}
