//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionAgenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfiguracionAgenda()
        {
            this.PlanillaDiaria = new HashSet<PlanillaDiaria>();
        }
    
        public int id { get; set; }
        public int duracionTurno { get; set; }
        public System.TimeSpan horaDesde { get; set; }
        public System.TimeSpan horaHasta { get; set; }
        public System.DateTime fechaDesde { get; set; }
        public System.DateTime fechaHasta { get; set; }
        public bool publicarWeb { get; set; }
        public bool esEspontanea { get; set; }
        public int idEspecialidad { get; set; }
        public int idSector { get; set; }
        public string diasAtencion { get; set; }
        public string usuarioCrea { get; set; }
        public System.DateTime fechaCrea { get; set; }
        public string usuarioModi { get; set; }
        public System.DateTime fechaModi { get; set; }
        public bool vigente { get; set; }
        public Nullable<int> idProfesional { get; set; }
        public Nullable<int> idPuestoTrabajo { get; set; }
        public string tipo { get; set; }
        public Nullable<int> cantDiasAnticipacion { get; set; }
        public Nullable<int> cantTurnosReservados { get; set; }
        public string nombre { get; set; }
        public string colorIndex { get; set; }
    
        public virtual Sectores Sectores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaDiaria> PlanillaDiaria { get; set; }
    }
}
