
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KlinicosDirectivos
{

using System;
    using System.Collections.Generic;
    
public partial class Establecimientos
{

    public int id { get; set; }

    public string nombre { get; set; }

    public int idLocalidad { get; set; }

    public string calle { get; set; }

    public string numeroPuerta { get; set; }

    public string otrasReferencias { get; set; }

    public string codPostal { get; set; }

    public bool vigente { get; set; }

    public string usuarioCrea { get; set; }

    public System.DateTime fechaCrea { get; set; }

    public string usuarioModi { get; set; }

    public System.DateTime fechaModi { get; set; }

    public string numero { get; set; }

    public string regionSanitaria { get; set; }

    public Nullable<int> MailSistema_Id { get; set; }

    public Nullable<int> MailSistemaSMTP_Id { get; set; }

    public string ApiBaseUrl { get; set; }

}

}
