//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvolucionesArchivos
    {
        public System.Guid idEvolucion { get; set; }
        public System.Guid idArchivo { get; set; }
    
        public virtual Evoluciones Evoluciones { get; set; }
    }
}
