//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaPlanillaDiaria
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Observacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int PlanillaDiariaRefId { get; set; }
    
        public virtual PlanillaDiaria PlanillaDiaria { get; set; }
    }
}
