//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observaciones
    {
        public System.Guid id { get; set; }
        public System.Guid idPaciente { get; set; }
        public Nullable<System.Guid> idProblemaSalud { get; set; }
        public int idProfesional { get; set; }
        public int idEstablecimiento { get; set; }
        public string usuarioCrea { get; set; }
        public System.DateTime fechaCrea { get; set; }
        public Nullable<System.Guid> idAtencion { get; set; }
        public Nullable<System.Guid> idAtencionesEstados { get; set; }
        public Nullable<System.Guid> idEvolucion { get; set; }
    
        public virtual Atenciones Atenciones { get; set; }
        public virtual AtencionesEstados AtencionesEstados { get; set; }
        public virtual Evoluciones Evoluciones { get; set; }
        public virtual ProblemasSalud ProblemasSalud { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
