//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObservacionAntropometrica
    {
        public System.Guid id { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int idSexo { get; set; }
        public decimal peso { get; set; }
        public decimal altura { get; set; }
        public Nullable<decimal> perimetroCintura { get; set; }
        public Nullable<decimal> perimetroCefalico { get; set; }
        public decimal imcValor { get; set; }
        public int percentilPeso { get; set; }
        public int percentilEstatura { get; set; }
        public int percentilPerimetroCefalico { get; set; }
        public int percentilIMC { get; set; }
        public string imc { get; set; }
    
        public virtual Observaciones Observaciones { get; set; }
    }
}
