
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KlinicosDirectivos
{

using System;
    using System.Collections.Generic;
    
public partial class Practicas
{

    public int id { get; set; }

    public string nombre { get; set; }

    public string especialidad { get; set; }

    public string cod_sumar { get; set; }

    public string tipo { get; set; }

    public bool vigente { get; set; }

    public string usuarioCrea { get; set; }

    public System.DateTime fechaCrea { get; set; }

    public string usuarioModi { get; set; }

    public System.DateTime fechaModi { get; set; }

    public string codigo_salud { get; set; }

}

}
