//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemasSalud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProblemasSalud()
        {
            this.Evoluciones = new HashSet<Evoluciones>();
            this.Observaciones = new HashSet<Observaciones>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid idPaciente { get; set; }
        public int idProfesional { get; set; }
        public int idSNOMed_problema { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public string epicrisis { get; set; }
        public bool activo { get; set; }
        public string usuarioCrea { get; set; }
        public System.DateTime fechaCrea { get; set; }
        public string usuarioModi { get; set; }
        public System.DateTime fechaModi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evoluciones> Evoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observaciones> Observaciones { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
