//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportesEspecialidades
    {
        public int id { get; set; }
        public int idReporte { get; set; }
        public int idEspecialidad { get; set; }
        public string html { get; set; }
        public string storeProcedure { get; set; }
        public string usuarioCrea { get; set; }
        public System.DateTime fechaCrea { get; set; }
    
        public virtual Especialidades Especialidades { get; set; }
        public virtual Reportes Reportes { get; set; }
    }
}
