//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicosDirectivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int Id { get; set; }
        public System.DateTime FechaYHora { get; set; }
        public Nullable<int> AtendidoEnRefId { get; set; }
        public Nullable<int> AtendidoPorRefId { get; set; }
        public Nullable<int> UltimoEstadoRefId { get; set; }
        public int PlanillaDiariaRefId { get; set; }
        public string clase { get; set; }
    
        public virtual Profesionales Profesionales { get; set; }
        public virtual TurnosReserva TurnosReserva { get; set; }
    }
}
