
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KlinicosDirectivos
{

using System;
    using System.Collections.Generic;
    
public partial class Turno
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Turno()
    {

        this.TurnoTurnoEstado1 = new HashSet<TurnoTurnoEstado>();

    }


    public int Id { get; set; }

    public System.DateTime FechaYHora { get; set; }

    public Nullable<int> AtendidoEnRefId { get; set; }

    public Nullable<int> AtendidoPorRefId { get; set; }

    public Nullable<int> UltimoEstadoRefId { get; set; }

    public int PlanillaDiariaRefId { get; set; }

    public string clase { get; set; }



    public virtual TurnoTurnoEstado TurnoTurnoEstado { get; set; }

    public virtual TurnosReserva TurnosReserva { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TurnoTurnoEstado> TurnoTurnoEstado1 { get; set; }

}

}
